require:
 - rubocop-performance
 - rubocop-rails
 - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config.ru'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/assets/**/*'
    - 'lib/tasks/**/*'
    - 'lib/templates/**/*'
    - 'node_modules/**/*'
    - 'Rakefile'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
Layout/LineLength:
  Enabled: False
Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*.rb'
    - 'app/services/**/*'

Metrics/BlockLength:
  CountComments: false
  Max: 5
  CountAsOne: ['array', 'hash']
  Exclude:
    - 'app/controllers/**/*'
    - 'app/views/**/*'
    - 'spec/**/*'
  AllowedMethods:
    - 'included'
    - 'context'
    - 'describe'
    - 'it'
    - 'shared_examples'
    - 'configure'
    - 'group'

Metrics/ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  Max: 100
  Enabled: true

Metrics/MethodLength:
  Description: 'Avoid methods longer than 5 lines of code.'
  StyleGuide: '<https://github.com/bbatsov/ruby-style-guide#short-methods>'
  Max: 5
  Enabled: true
  CountAsOne: ['array', 'hash', 'heredoc']
  Exclude:
    - 'app/controllers/**/*'

Metrics/ParameterLists:
  Description: 'Pass no more than four parameters into a method.'
  Max: 4

Naming/VariableNumber:
  Enabled: false

Rails/DynamicFindBy:
  Whitelist:
    - find_by_airtable_id
    - find_by_dimension_key
Rails/HasAndBelongsToMany:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/ExampleLength:
  Max: 5
  CountAsOne: ['array', 'hash']
RSpec/NestedGroups:
  Max: 6
RSpec/RepeatedDescription:
  Exclude:
    - 'spec/policies/**'
RSpec/RepeatedExample:
  Exclude:
    - 'spec/policies/**'
Style/AsciiComments: # Let the man shrug! ¯\_(ツ)_/¯
  Enabled: False
Style/ClassAndModuleChildren:
  Enabled: True
  Exclude:
    - 'app/components/**/*'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Lambda:
  EnforcedStyle: literal
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
